#!/usr/bin/env python3
"""Render the operation reference from the schemas used by both public interfaces."""

import argparse
import json
from pathlib import Path

from icloud_agent.operations import OPERATIONS

ROOT = Path(__file__).resolve().parents[1]


def type_label(schema):
    if "anyOf" in schema:
        return " or ".join(type_label(value) for value in schema["anyOf"])
    if schema.get("type") == "array":
        return f"array of {type_label(schema['items'])}"
    return schema.get("type", "object")


def generate():
    lines = [
        "# CLI and MCP operation reference",
        "",
        "[← README](../README.md) · [Usage examples](usage.md) · [Agent setup](clients.md)",
        "",
        "Generated by `scripts/generate_reference.py` from the runtime operation registry.",
        "Edit schemas/descriptions in the code, then regenerate this file.",
        "",
        "CLI: `icloud-agent CATEGORY ACTION --input FILE`. Omit the input for an empty object.",
        "Generic CLI: `icloud-agent call OPERATION --input FILE`. Use `--input -` for stdin.",
        "MCP: invoke the named tool with `arguments` containing the same input object.",
        "All input schemas reject unknown fields and enforce strict JSON types.",
        "",
        "`--dry-run` validates schemas only. `icloud-agent schema OPERATION` returns the live",
        "JSON Schema. [All generated schemas](tool-schemas.json) are also checked into this repo.",
        "",
        "## Account and utility commands",
        "",
        "| Command | Behavior |",
        "|---|---|",
        "| `setup [--codex] [--skills] [--agent NAME] [--copy]` | Export bundled plugin; register Codex MCP or install the shared skill and optional agent links. `--agent` is repeatable and requires `--skills`. |",
        "| `auth login [--no-browser]` | Interactive local setup; IMAP/CalDAV checked before saving. |",
        "| `auth status [--check]` | Local credential presence; optionally live IMAP/CalDAV checks. |",
        "| `auth configure` | Reload addresses/calendars and choose enabled resources. |",
        "| `auth logout` | Remove active local credential and account config. |",
        "| `auth web-login` | Experimental interactive Apple Account password and device/SMS 2FA. |",
        "| `auth web-status` | Validate the separate saved web session against Apple. |",
        "| `auth web-check` | Diagnostic read-only alias and Mail folder requests. |",
        "| `auth web-logout` | Remove this tool's local web session. |",
        "| `schema [OPERATION]` | Describe operation inputs without authentication. |",
        "| `mcp` | Start a local stdio MCP process. |",
        "| `--version` / `--help` | Human-readable version/help. |",
        "",
        "## Operations",
        "",
        "| MCP tool | CLI command | Access |",
        "|---|---|---|",
    ]
    schemas = {}
    for name, operation in OPERATIONS.items():
        category, action = name.split("_", 1)
        cli = f"{category} {action.replace('_', '-')}"
        lines.append(
            f"| [`{name}`](#{name}) | `{cli}` | {'Write' if operation.write else 'Read'} |"
        )
        schemas[name] = {
            "description": operation.description,
            "write": operation.write,
            "destructive": operation.destructive,
            "input_schema": operation.model.model_json_schema(),
        }
    for name, operation in OPERATIONS.items():
        lines += ["", f"## {name}", "", operation.description, ""]
        fields = operation.model.model_fields
        if not fields:
            lines += ["Input: `{}`."]
            continue
        lines += ["| Field | Type | Required | Default | Constraints |", "|---|---|---|---|---|"]
        schema = schemas[name]["input_schema"]
        for field_name, model_field in fields.items():
            field = schema["properties"][field_name]
            constraints = {
                k: v
                for k, v in field.items()
                if k
                in (
                    "minimum",
                    "maximum",
                    "minLength",
                    "maxLength",
                    "minItems",
                    "maxItems",
                    "pattern",
                )
            }
            required = model_field.is_required()
            default = (
                "—"
                if required
                else "`" + json.dumps(model_field.get_default(call_default_factory=True)) + "`"
            )
            constraint = "; ".join(f"{k}: `{v}`" for k, v in constraints.items()) or "—"
            lines.append(
                f"| `{field_name}` | {type_label(field)} | {'Yes' if required else 'No'} | {default} | {constraint} |"
            )
    lines += [
        "",
        "## Results and recovery",
        "",
        "Results use `ok` plus `data` or `error`; the payload inside `data` is operation-specific.",
        "Read `ok` even when the MCP transport succeeded. See [usage](usage.md#output-and-exit-codes)",
        "for envelopes/exit codes and [troubleshooting](troubleshooting.md) for error recovery.",
        "Opaque IDs, ETags, and hashes must be copied exactly from results. A `verified:false`",
        "write result requires readback; it does not authorize a repeat mutation.",
        "",
    ]
    return {
        ROOT / "docs/reference.md": "\n".join(lines),
        ROOT / "docs/tool-schemas.json": json.dumps(schemas, indent=2, ensure_ascii=False) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outdated = []
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                outdated.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if outdated:
        parser.exit(1, "Regenerate operation docs: " + ", ".join(outdated) + "\n")
    print("Operation reference and schemas are current.")


if __name__ == "__main__":
    main()
